const Engine={objects:[],time:0,dt:120,integratorType:"RK4",gravityAlgorithm:"BARNES_HUT",status:"STABLE",paused:false,frames:0,lastFpsTime:0,adaptiveDt:false,minDt:1e-6,maxDt:1e12,safety:.2,activeModels:["Gravity","Collision","Nuclear","Thermodynamics"],
setIntegrator:function(type){this.integratorType=String(type).toUpperCase();},
getAccelerations:function(objs){const a=new Array(objs.length).fill(null).map(()=>new Vec3());if(this.activeModels.includes("Gravity")){const g=GravityEngine.computeAccelerations(objs,this.gravityAlgorithm==="BARNES_HUT");for(let i=0;i<objs.length;i++)a[i]=a[i].add(g[i]);}if(this.activeModels.includes("Relativity")){const g=RelativityEngine.computeSchwarzschildPrecession(objs);for(let i=0;i<objs.length;i++)a[i]=a[i].add(g[i]);}if(this.activeModels.includes("Electromagnetic")){const g=ElectromagneticEngine.computeAccelerations(objs);for(let i=0;i<objs.length;i++)a[i]=a[i].add(g[i]);}return a;},
step:function(){if(this.status==="FAILED"||this.paused)return;for(const o of this.objects){if(![o.pos.x,o.pos.y,o.pos.z,o.vel.x,o.vel.y,o.vel.z].every(Number.isFinite)){this.status="FAILED";throw new Error("Non-finite state detected");}if(o.vel.magSq()>=PhysicsConstants.c**2){this.status="FAILED";throw new Error("Superluminal velocity detected");}}if(!(this.dt>0&&Number.isFinite(this.dt)&&this.dt>=this.minDt&&this.dt<=this.maxDt)){this.status="FAILED";throw new Error("Invalid timestep");}const t=String(this.integratorType).toLowerCase();if(t==="euler")Integrators.eulerSemiImplicit(this.objects,this.dt,this.getAccelerations(this.objects));else if(t==="verlet")Integrators.verlet(this.objects,this.dt,obs=>this.getAccelerations(obs));else if(t==="rk4")Integrators.rk4(this.objects,this.dt,obs=>this.getAccelerations(obs));else{this.status="FAILED";throw new Error("Unknown integrator: "+this.integratorType);}if(this.activeModels.includes("Fluid"))FluidEngine.computeSPH(this.objects);if(this.activeModels.includes("Nuclear"))NuclearEngine.computeFusion(this.dt,this.objects);if(this.activeModels.includes("Collision"))CollisionEngine.checkAndResolve(this.objects);if(this.activeModels.includes("Thermodynamics")){ThermoEngine.updateTemperature(this.objects);ThermoEngine.computeRadiation(this.dt,this.objects);}if(this.adaptiveDt){let amin=Infinity;for(const o of this.objects){const a=o.acc.mag();if(a>0)amin=Math.min(amin,Math.sqrt(Math.max(o.radius,1)/a));}if(Number.isFinite(amin))this.dt=Math.max(this.minDt,Math.min(this.maxDt,this.safety*amin));}this.time+=this.dt;Diagnostics.update(this.objects);UI.updateInspector();},
togglePause:function(){if(this.status==="FAILED"){this.status="STABLE";this.paused=false;Diagnostics.begin(this.objects);}else this.paused=!this.paused;this.syncPauseButton();},
resetFailure:function(){this.status="STABLE";this.paused=false;Diagnostics.begin(this.objects);this.syncPauseButton();},
syncPauseButton:function(){const b=document.getElementById("btn-pause");if(b)b.innerText=this.paused?"재개 (RESUME)":"일시정지 (PAUSE)";},
setModel:function(name,enabled){const i=this.activeModels.indexOf(name);if(enabled&&i<0)this.activeModels.push(name);if(!enabled&&i>=0)this.activeModels.splice(i,1);},
loop:function(){requestAnimationFrame(()=>this.loop());if(!this.paused){try{this.step();}catch(e){this.status="FAILED";this.paused=true;this.syncPauseButton();const statusEl=document.getElementById("diag-status");if(statusEl){statusEl.innerText="FAILED";statusEl.className="val fail";}}}Renderer.draw();}};
